server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.10.111:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  kafka:
    bootstrap-servers: 192.168.10.111:29092
    group-id: group-id-fluent-bit # ???? ???? ??? ? ?? ?

  redis:
    host: 192.168.10.111
    port: 6379
  cache:
    type: redis

slack:
  token: xoxb-6173205612421-6161622726311-Nney0um4cD4dNnTBlT09e48D
  channel: log

search:
  algorithm : KnuthMorrisPratt

message:
  topic:
    name: test