server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.10.111:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

  redis:
    host: 192.168.10.111
    port: 6379

slack:
  token: xoxb-6173205612421-6161622726311-DKwXclC0mtkTF4uagL3kKyzn
  channel: log

search:
  algorithm : KnuthMorrisPratt
